# data
data_file: ut_har
num_classes: 7
transform1: noise
transform2: magnify

# train hyperparameters
batch_size: 1024
epochs: 100
optimizer: adam
temperature: 0.0001
learning_rate: 0.0001

# save path
save_path: checkpoints/


